language: java
dist: trusty

# don't just run the tests, also run error-prone
script: ./mvnw -B verify

jdk:
- openjdk8
- openjdk11
- openjdk14

notifications:
  email:
    recipients:
      - ryan@10e.us

