language: java

before_install: sudo pip install codecov

install: echo "I trust Maven."

# don't just run the tests, also run Findbugs and friends
script: mvn verify

jdk:
  - oraclejdk7
  - oraclejdk8

after_success: codecov

notifications:
  email:
    recipients:
      - ryan@10e.us
