---
name: "Qodana"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - 'release/*'

jobs:
  qodana:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      pull-requests: "write"
      checks: "write"
      security-events: "write"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@e42ff2d2727091337983f607598abbbce4e25f1f # v2023.3.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - uses: github/codeql-action/upload-sarif@1b1aada464948af03b950897e5eb522f92603cc2 # v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
