---
name: "Qodana"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - 'release/*'

jobs:
  qodana:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      pull-requests: "write"
      checks: "write"
      security-events: "write"
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - uses: github/codeql-action/upload-sarif@5b6282e01c62d02e720b81eb8a51204f527c3624 # v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
